swagger: "2.0"
info:
  description: "Write\
    \ description\
    \ here."
  version: "0.0.1"
  title: "rndm"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: ""
  license:
    name: ""
    url: ""
host: ""
basePath: "/v1"
tags:
  - name: "rndm"
    description: "Let rndm pick an item from your list"
    externalDocs:
      description: ""
      url: ""
schemes:
  - "http"
paths:
  /list:
    post:
      tags:
        - "list"
      summary: "Add list"
      description: ""
      operationId: "addList"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "List with items"
          required: true
          schema:
            $ref: "#/definitions/List"
      responses:
        400:
          description: "Bad request"
#      security:
#        - petstore_auth:
#            - "write:pets"
#            - "read:pets"

#securityDefinitions:
#  petstore_auth:
#    type: "oauth2"
#    authorizationUrl: "http://petstore.swagger.io/api/oauth/dialog"
#    flow: "implicit"
#    scopes:
#      write:pets: "modify pets in your account"
#      read:pets: "read your pets"
#  api_key:
#    type: "apiKey"
#    name: "api_key"
#    in: "header"
definitions:
  List:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        format: "int64"
#  ApiResponse:
#    type: "object"
#    properties:
#      code:
#        type: "integer"
#        format: "int32"
#      type:
#        type: "string"
#      message:
#        type: "string"
#externalDocs:
#  description: "Find out more about Swagger"
#  url: "http://swagger.io"